# docker-compose.yml
version: "3"
services:
  backend:
    image: devopscu/backend:latest
    container_name: "devopscu-backend"
    restart: always
    environment:
      MongoURL: mongodb+srv://devopscu:devopscu_read_user@cluster0.8iqoa.mongodb.net/dbbackend
      TZ: "Europe/Istanbul"
    ports:
      - 8081:3000
